Repository ds-wizard/dsw-server, pull requests merged in 2018-12, with the labels that each got.

#28 Release 1.1.0 (develop)
  package.yaml
Labels: release

#30 Upgrade Stack to 1.9.3
  .travis.yml
Labels: chore

#31 [DSW-161] Retry connect to MongoDB, RabbitMQ on start
  lib/Application.hs
  lib/Database/Connection.hs
  package.yaml
  test/Spec.hs
Labels: feature
