Repository ds-wizard/dsw-server, pull requests merged in 2019-08, with the labels that each got.

#88 Release 1.9.0 (develop)
  lib/Database/Migration/Production/Migration_0022_forkOfPackageId_and_mergeCheckpointPackageId/Migration.hs
  lib/Service/Package/PackageMapper.hs
  lib/Service/Package/PackageUtils.hs
  lib/Service/Package/PackageValidation.hs
  lib/Service/Version/VersionMapper.hs
  lib/Service/Version/VersionService.hs
  package.yaml
  vendor/dsw-metamodel-migrator/package.yaml
Labels: release

#90 Hotfix 1.9.1 (develop)
  lib/Util/JSON.hs
Labels: hotfix

#89 Hotfix 1.9.1
  lib/Util/JSON.hs
Labels: hotfix

#91 [DSW-493] Config option appTitle in mail template
  lib/Localization.hs
  lib/Service/Mail/Mailer.hs
  templates/mail/_common/layout.html.j2
Labels: feature

#92 Hotfix 1.9.2
  lib/Model/Config/AppConfigDM.hs
  package.yaml
Labels: hotfix

#93 Hotfix 1.9.2 (develop)
  lib/Model/Config/AppConfigDM.hs
  package.yaml
Labels: hotfix
