Repository ds-wizard/dsw-server, pull requests merged in 2019-05, with the labels that each got.

#68 [DSW-314] Configurable phases
  config/application-test.yml.example
  config/application.yml.example
  lib/Api/Resource/Config/ClientConfigDTO.hs
  lib/Api/Resource/Config/ClientConfigJM.hs
  lib/Database/Migration/Development/DataManagementPlan/Data/DataManagementPlans.hs
  lib/Database/Migration/Development/Report/Data/Reports.hs
  lib/Model/Config/AppConfig.hs
  lib/Service/Config/ClientConfigMapper.hs
  lib/Service/DataManagementPlan/DataManagementPlanService.hs
  lib/Service/Package/PackageMapper.hs
  test/Spec.hs
  test/Specs/Service/DataManagementPlan/Common.hs
  test/Specs/Service/DataManagementPlan/DataManagementPlanServiceSpec.hs
Labels: feature

#72 Release 1.6.0 v2 (develop)
  lib/Service/Migration/Metamodel/Migrator/BranchMigrator.hs
  lib/Service/Migration/Metamodel/Migrator/KnowledgeModelBundleMigrator.hs
  lib/Service/Migration/Metamodel/Migrator/KnowledgeModelMigrationMigrator.hs
  lib/Service/Migration/Metamodel/Migrator/PackageMigrator.hs
  lib/Service/Migration/Metamodel/MigratorService.hs
  package.yaml
Labels: release

#73 [DSW-316][DSW-325] Add support for configurable features in the template
  templates/dmp/root.css
  templates/dmp/root.html.j2
Labels: feature

#76 Release 1.7.0 (develop)
  package.yaml
Labels: release

#78 Metamodel Migration 2 -> 3
  lib/Constant/KnowledgeModel.hs
  vendor/dsw-metamodel-migrator/package.yaml
  vendor/dsw-metamodel-migrator/src/DSW/Metamodel/Event/Version1.hs
  vendor/dsw-metamodel-migrator/src/DSW/Metamodel/Event/Version2.hs
  vendor/dsw-metamodel-migrator/src/DSW/Metamodel/Event/Version3.hs
  vendor/dsw-metamodel-migrator/src/DSW/Metamodel/Migration/Migration1.hs
  vendor/dsw-metamodel-migrator/src/DSW/Metamodel/Migration/Migration2.hs
  vendor/dsw-metamodel-migrator/src/DSW/Metamodel/Migrator/EventMigrator.hs
Labels: chore
