Repository ds-wizard/dsw-server, pull requests merged in 2019-04, with the labels that each got.

#56 [DSW-276] Notification when mailer fails to send email
  lib/Localization.hs
  lib/Service/Mail/Mailer.hs
  lib/Service/User/UserService.hs
Labels: feature

#57 Upgrade to Ubuntu 16.04 (Xenial Xerus)
  .travis.yml
  Dockerfile
Labels: chore

#60 Release 1.5.0 (develop)
  package.yaml
  vendor/dsw-metamodel-migrator/package.yaml
Labels: release

#59 Release 1.5.0
  .travis.yml
  Dockerfile
  config/app-config-test.cfg.example
  config/app-config.cfg.example
  lib/Api/Resource/FilledKnowledgeModel/FilledKnowledgeModelDTO.hs
  lib/Api/Resource/Questionnaire/QuestionnaireChangeDTO.hs
  lib/Api/Resource/Questionnaire/QuestionnaireChangeJM.hs
  lib/Application.hs
  lib/Database/Connection.hs
  lib/Database/Migration/Development/FilledKnowledgeModel/Data/FilledAnswersAndFollowUpQuestions.hs
  lib/Database/Migration/Development/FilledKnowledgeModel/Data/FilledChapters.hs
  lib/Database/Migration/Development/FilledKnowledgeModel/Data/FilledQuestions.hs
  lib/Database/Migration/Development/Questionnaire/Data/Questionnaires.hs
  lib/Localization.hs
  lib/Messaging/Connection.hs
  lib/Messaging/Out/Topic/Common.hs
  lib/Model/Config/AppConfig.hs
  lib/Model/Context/AppContext.hs
  lib/Model/Context/BaseContext.hs
  lib/Model/FilledKnowledgeModel/FilledKnowledgeModel.hs
  lib/Service/Config/ConfigLoader.hs
  lib/Service/DataManagementPlan/Convertor.hs
  lib/Service/DataManagementPlan/ReplyApplicator.hs
  lib/Service/Feedback/Connector/GitHub/GitHubConnector.hs
  lib/Service/Feedback/Connector/GitHub/GitHubMapper.hs
  lib/Service/FilledKnowledgeModel/FilledKnowledgeModelMapper.hs
  lib/Service/Mail/Mailer.hs
  lib/Service/Questionnaire/QuestionnaireMapper.hs
  lib/Service/Token/TokenService.hs
  lib/Service/User/UserService.hs
  lib/Util/Alphabet.hs
  package.yaml
  stack.yaml
  templates/dmp/root.css
  templates/dmp/root.html.j2
  test/Specs/API/Questionnaire/Detail_PUT.hs
  test/Specs/API/Questionnaire/Detail_Report_Preview_POST.hs
  vendor/dsw-metamodel-migrator/.gitignore
  vendor/dsw-metamodel-migrator/LICENSE
  vendor/dsw-metamodel-migrator/Setup.hs
  vendor/dsw-metamodel-migrator/package.yaml
  vendor/dsw-metamodel-migrator/src/DSW/Metamodel/Migrator/EventMigrator.hs
  vendor/dsw-metamodel-migrator/stack.yaml
  vendor/mongoDB-migration/stack.yaml
Labels: release

#58 [DSW-294] Email inline images compatibility
  lib/Constant/Mailer.hs
  lib/Localization.hs
  lib/Service/Mail/Mailer.hs
  package.yaml
  stack.yaml
  templates/mail/_common/images/logo.png
Labels: feature

#61 [DSW-288] Travis build review and speedup
  .travis.yml
  Dockerfile
Labels: chore

#65 [DSW-297] KM Events migration V1 -> V2
  lib/Constant/KnowledgeModel.hs
  vendor/dsw-metamodel-migrator/package.yaml
  vendor/dsw-metamodel-migrator/src/DSW/Metamodel/Event/Version1.hs
  vendor/dsw-metamodel-migrator/src/DSW/Metamodel/Event/Version2.hs
  vendor/dsw-metamodel-migrator/src/DSW/Metamodel/Migration/Migration1.hs
  vendor/dsw-metamodel-migrator/src/DSW/Metamodel/Migrator/EventMigrator.hs
Labels: feature

#64 [DSW-291] Add integration logo and link to the DMP template
  templates/dmp/root.css
  templates/dmp/root.html.j2
Labels: feature
