Repository ds-wizard/dsw-server, pull requests merged in 2019-03, with the labels that each got.

#45 [DSW-236] Email templates
  Dockerfile
  lib/Constant/Mailer.hs
  lib/Localization.hs
  lib/Service/Mail/Mailer.hs
  lib/Service/Template/TemplateService.hs
  lib/Service/User/UserService.hs
  lib/Util/Template.hs
  package.yaml
  templates/dmp/root.css
  templates/dmp/root.html.j2
  templates/mail/_common/attachments/logo.png
  templates/mail/_common/footer.txt.j2
  templates/mail/_common/layout.html.j2
  templates/mail/_common/style.css
  templates/mail/registrationConfirmation/message.html.j2
  templates/mail/registrationConfirmation/message.txt.j2
  templates/mail/registrationCreatedAnalytics/message.html.j2
  templates/mail/registrationCreatedAnalytics/message.txt.j2
  templates/mail/resetPassword/message.html.j2
  templates/mail/resetPassword/message.txt.j2
Labels: feature

#51 Release 1.4.0 (develop)
  package.yaml
Labels: release

#52 [DSW-242] Change name and visibility of a questionnaire
  lib/Api/Resource/Questionnaire/QuestionnaireChangeDTO.hs
  lib/Api/Resource/Questionnaire/QuestionnaireChangeJM.hs
  lib/Database/Migration/Development/Questionnaire/Data/Questionnaires.hs
  lib/Service/Questionnaire/QuestionnaireMapper.hs
  test/Specs/API/Questionnaire/Detail_PUT.hs
  test/Specs/API/Questionnaire/Detail_Report_Preview_POST.hs
Labels: feature

#49 Update LTS Haskell
  .travis.yml
  Dockerfile
  lib/Service/Feedback/Connector/GitHub/GitHubConnector.hs
  lib/Service/Feedback/Connector/GitHub/GitHubMapper.hs
  lib/Service/Token/TokenService.hs
  package.yaml
  stack.yaml
Labels: chore

#54 Fix Travis CI caching of Stack
  .travis.yml
Labels: chore

#53 [DSW-265] Make RabbitMQ optional
  config/app-config-test.cfg.example
  config/app-config.cfg.example
  lib/Application.hs
  lib/Messaging/Connection.hs
  lib/Messaging/Out/Topic/Common.hs
  lib/Model/Config/AppConfig.hs
  lib/Model/Context/AppContext.hs
  lib/Model/Context/BaseContext.hs
  lib/Service/Config/ConfigLoader.hs
Labels: feature
