Repository ds-wizard/dsw-server, pull requests merged in 2019-09, with the labels that each got.

#98 Release 1.10.0 (develop)
  dsw-metamodel-migrator/package.yaml
  dsw-server/package.yaml
Labels: release

#99 Add building Docker images from branches
  .travis.yml
Labels: chore

#101 Hotfix 1.10.1
  dsw-server/package.yaml
  dsw-server/templates/dmp/root.html.j2
Labels: hotfix

#102 Hotfix 1.10.1 (develop)
  dsw-server/package.yaml
  dsw-server/templates/dmp/root.html.j2
Labels: hotfix
